package BNALang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAsset = createDescriptorForAsset();
  /*package*/ final ConceptDescriptor myConceptParticipant = createDescriptorForParticipant();
  /*package*/ final ConceptDescriptor myConceptSmartContract = createDescriptorForSmartContract();
  /*package*/ final ConceptDescriptor myConceptString = createDescriptorForString();
  /*package*/ final ConceptDescriptor myConceptTransaction = createDescriptorForTransaction();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAsset, myConceptParticipant, myConceptSmartContract, myConceptString, myConceptTransaction);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Asset:
        return myConceptAsset;
      case LanguageConceptSwitch.Participant:
        return myConceptParticipant;
      case LanguageConceptSwitch.SmartContract:
        return myConceptSmartContract;
      case LanguageConceptSwitch.String:
        return myConceptString;
      case LanguageConceptSwitch.Transaction:
        return myConceptTransaction;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAsset() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BNALang", "Asset", 0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83992cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:da556fcd-83c8-41d5-9fb7-1cc44bb39ea9(BNALang.structure)/1975795149174970668");
    b.version(2);
    b.property("identifiedBy", 0x1b6b6f384f83a907L).type(PrimitiveTypeId.STRING).origin("1975795149174974727").done();
    b.associate("indentifiedBy", 0x1b6b6f384f83e674L).target(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83e1f6L).optional(true).origin("1975795149174990452").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParticipant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BNALang", "Participant", 0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:da556fcd-83c8-41d5-9fb7-1cc44bb39ea9(BNALang.structure)/1975795149174971297");
    b.version(2);
    b.property("identifiedBy", 0x1b6b6f384f83a90cL).type(PrimitiveTypeId.STRING).origin("1975795149174974732").done();
    b.property("abstract", 0x1b6b6f384f83a90eL).type(PrimitiveTypeId.BOOLEAN).origin("1975795149174974734").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSmartContract() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BNALang", "SmartContract", 0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f8394f6L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:da556fcd-83c8-41d5-9fb7-1cc44bb39ea9(BNALang.structure)/1975795149174969590");
    b.version(2);
    b.property("namespace", 0x1b6b6f384f83a1d0L).type(PrimitiveTypeId.STRING).origin("1975795149174972880").done();
    b.aggregate("assets", 0x1b6b6f384f83992fL).target(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83992cL).optional(true).ordered(true).multiple(true).origin("1975795149174970671").done();
    b.aggregate("participants", 0x1b6b6f384f839ba4L).target(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L).optional(true).ordered(true).multiple(true).origin("1975795149174971300").done();
    b.aggregate("transactions", 0x1b6b6f384f83a1ccL).target(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83a1c5L).optional(true).ordered(true).multiple(true).origin("1975795149174972876").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BNALang", "String", 0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83e1f6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:da556fcd-83c8-41d5-9fb7-1cc44bb39ea9(BNALang.structure)/1975795149174989302");
    b.version(2);
    b.property("value", 0x1b6b6f384f83e1f9L).type(PrimitiveTypeId.STRING).origin("1975795149174989305").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransaction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BNALang", "Transaction", 0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83a1c5L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:da556fcd-83c8-41d5-9fb7-1cc44bb39ea9(BNALang.structure)/1975795149174972869");
    b.version(2);
    b.associate("String", 0x1b6b6f384f83e208L).target(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f83e1f6L).optional(true).origin("1975795149174989320").done();
    return b.create();
  }
}
