package BNALang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Participant_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f83a90eL, "abstract"))) {
      tgs.append("abstract ");
    }
    tgs.append("participant ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f8420fbL, "extends")) != null) {
      tgs.append(" extends ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f8420fbL, "extends")));
    }
    if (SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f83a90cL, "identifiedBy")) != null) {
      tgs.append(" indentified by ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f83a90cL, "identifiedBy")));
    }
    tgs.append(" {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x2eaecd5c01894365L, 0x9c9c356775610810L, 0x1b6b6f384f839ba1L, 0x1b6b6f384f83fe2fL, "attributes"))) {
      tgs.appendNode(item);
    }
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
    tgs.newLine();
  }
}
